version: '2'

services:
  core:
    build: core/
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - '8080:8080'
    volumes:
      - ./core:/app
  redis:
    image: docker.io/bitnami/redis:6.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'

volumes:
  redis_data:
    driver: local
